#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/share/common.sh

# Run the terasort action on resourcemanager
printf "\nTerasort benchmark submitted.\n"
ID=`juju run-action resourcemanager/0 terasort | awk '{print $5}'`

# Display the action output
juju show-action-output $ID

# TODO: Use a better Juju Wait for the action to comoplete
printf "\nTerasort action running. This may take a few minutes to complete. "

STATUS=`juju show-action-output $ID | grep status | awk '{print $2}'`
while [ "$STATUS"=="pending" ]; do
  printf ". "
  sleep 10s
done
echo "Terasort benchmark complete:\n"
juju show-action-output $ID
