#!/bin/bash

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

tmpfile=$(mktemp)

cat "$CONJURE_UP_SPELLSDIR/sdk/common.sh" > "$tmpfile"

"$(scriptPath)/../novarc" >> "$tmpfile"

cat "$(scriptPath)/neutron.sh" >> "$tmpfile"

juju scp -m "$JUJU_CONTROLLER:$JUJU_MODEL" "$(scriptPath)/neutron-ext-net" nova-cloud-controller/0:.
juju scp -m "$JUJU_CONTROLLER:$JUJU_MODEL" "$(scriptPath)/neutron-tenant-net" nova-cloud-controller/0:.
juju scp -m "$JUJU_CONTROLLER:$JUJU_MODEL" "$tmpfile" nova-cloud-controller/0:neutron.sh
neutron_out=$(juju ssh -m "$JUJU_CONTROLLER:$JUJU_MODEL" nova-cloud-controller/0 "bash neutron.sh")
setResult "$neutron_out"
exit 0
