#!/bin/bash

set -eu

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/../../sdk/common.sh

juju wait -m $JUJU_CONTROLLER:$JUJU_MODEL

exposeResult "Applications Ready" 0 "true"
