#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

if [[ "$JUJU_PROVIDERTYPE" == "lxd" ]]; then
    printf "Running pre-deploy for LXD container"
    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | conjure-up.lxc profile edit "juju-$JUJU_MODEL"
fi

setResult "Successful pre-deploy"
exit 0
