#!/bin/bash

set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

if [[ "$JUJU_PROVIDERTYPE" == "lxd" ]]; then
    printf "Running pre-deploy for LXD container\n"
    lxc storage create conjureup dir || printf "conjureup storage pool already exists, skipping"
    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL"
fi

printf "result: Successful pre-deploy"
exit 0
