#!/bin/bash

set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

if [[ "$JUJU_PROVIDERTYPE" == "lxd" ]]; then
    printf "Running pre-deploy for LXD container\n"
    lxc storage create conjureup dir || true
    sed "s/##MODEL##/$JUJU_MODEL/" $(scriptPath)/lxd-profile.yaml | lxc profile edit "juju-$JUJU_MODEL" || printf "result: Failed to set profile" && exit 1
fi

printf "result: Successful pre-deploy"
exit 0
