#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/common.sh

args=""
if [ -f ~/.kube/config.conjure-up ]; then
    args="--kubeconfig=$HOME/.kube/config.conjure-up"
fi

NODES="$(~/kubectl $args get nodes | perl -p -e 's/\n/\\n/')"
PODS="$(~/kubectl $args get --all-namespaces pods | perl -p -e 's/\n/\\n/')"
SERVICES="$(~/kubectl $args get --all-namespaces services | perl -p -e 's/\n/\\n/')"

result="Nodes:\n$NODES\nPods:\n$PODS\nServices:\n$SERVICES"

exposeResult "$result" 0 "true"
