kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jfrogstandard
  annotations: 
    storageclass.beta.kubernetes.io/is-default-class: "false" 
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Retain
mountOptions:
  - debug
