#!/bin/bash
set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

TEST_LOG="openstack-verify.log"

testLog "Verifying bionic images are imported"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL \
     nova-cloud-controller/0 "source novarc && glance image-list --property-filter name=\"bionic-lxd\" | grep -q \"bionic-lxd\"" > $TEST_LOG 2>&1

testLog "Verifying xenial images are imported"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL \
     nova-cloud-controller/0 "source novarc && glance image-list --property-filter name=\"xenial-lxd\" | grep -q \"xenial-lxd\"" >> $TEST_LOG 2>&1

testLog "Verify ssh key imported"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL \
     nova-cloud-controller/0 "source novarc && openstack keypair show ubuntu-keypair" >> $TEST_LOG 2>&1

testLog "Verify creating a compute node"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL \
     nova-cloud-controller/0 "source novarc && nova boot --image xenial --flavor m1.tiny --key-name ubuntu-keypair --nic net-id=$(neutron net-list | grep internal | awk '{ print $2 }') xenial-test" >> $TEST_LOG 2>&1

testLog "Verify access to the node"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL \
     nova-cloud-controller/0 "source novarc && nova ssh ubuntu@xenial-test ping -c 1 ubuntu.com" >> $TEST_LOG 2>&1
