#!/bin/bash
set -eu

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

testLog "Verifying trusty images are imported"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-cloud-controller/0 "source novarc && glance image-list --property-filter name=\"trusty-lxd\" | grep -q \"trusty-lxd\""

testLog "Verifying xenial images are imported"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-cloud-controller/0 "source novarc && glance image-list --property-filter name=\"xenial-lxd\" | grep -q \"xenial-lxd\""

testLog "Verify ssh key imported"
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-cloud-controller/0 "source novarc && openstack keypair show ubuntu-keypair > /dev/null 2>&1"
