#!/bin/bash

set -eu
. $CONJURE_UP_SPELLSDIR/sdk/common.sh

if ! juju wait -vwm $JUJU_CONTROLLER:$JUJU_MODEL; then
    printf "Applications did not start successfully"
    exit 1
fi

printf "result: Applications Ready"
exit 0
