#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/share/common.sh

horizon_ip=$(unitAddress openstack-dashboard 0)

exposeResult "Login to Horizon: http://$horizon_ip/horizon l: admin p: openstack" 0 "true"
