#!/bin/bash

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

if juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-cloud-controller/0 "sudo apt-get -y install python{,3}-designateclient" >/dev/null 2>/dev/null; then
  exposeResult "Successfully installed Designate client" 0 "true"
else
  exposeResult "Error installing Designate client" 1 "false"
fi
