#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

juju scp $SCRIPTPATH/novarc neutron-api/0:.
juju ssh neutron-api/0 "bash -s" -- < $SCRIPTPATH/step-04_neutron.ssh

exit 0
