#!/bin/bash

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

tmpfile=$(mktemp)

cat <<EOF > $tmpfile
sudo apt-add-repository cloud-archive:pike -y > /dev/null/ 2>&1
sudo apt update > /dev/null 2>&1
sudo apt -qyf install python-novaclient python-keystoneclient python-glanceclient python-neutronclient python-openstackclient > /dev/null 2>&1
EOF

$(scriptPath)/share/novarc > "$tmpfile"

# Copy over credentials early
juju scp -m "$JUJU_CONTROLLER:$JUJU_MODEL" "$tmpfile" nova-cloud-controller/0:novarc

cat $(scriptPath)/share/common.sh >> "$tmpfile"
cat $(scriptPath)/share/glance.sh >> "$tmpfile"

juju scp -m "$JUJU_CONTROLLER:$JUJU_MODEL" "$tmpfile" nova-cloud-controller/0:glance.sh
glance_out=$(juju ssh -m "$JUJU_CONTROLLER:$JUJU_MODEL" nova-cloud-controller/0 "bash glance.sh")
setResult "$glance_out"
exit 0
