#!/bin/bash

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

if ! $(scriptPath)/share/patch-nova-lxd.py; then
  exposeResult "Error patching nova-compute containers for Docker support" 1 "false"
fi

tmpfile=$(mktemp)

cat $(scriptPath)/share/common.sh > $tmpfile
cat $(scriptPath)/share/nova_lxd_nova_virt_lxd_config.sh >> $tmpfile

juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL $tmpfile nova-compute/0:docker.sh
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-compute/0 "bash docker.sh"
