#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

tmpfile=$(mktemp)

cat <<EOF> $tmpfile
sudo apt update > /dev/null 2>&1
sudo apt -qyf install python3-openstackclient > /dev/null 2>&1
export SSHPUBLICKEY=$SSHPUBLICKEY
EOF

$SCRIPTPATH/share/novarc >> $tmpfile
cat $SCRIPTPATH/share/common.sh >> $tmpfile
cat $SCRIPTPATH/share/keypair.sh >> $tmpfile

juju scp $SSHPUBLICKEY nova-cloud-controller/0:.ssh/.
juju scp $tmpfile nova-cloud-controller/0:keypair.sh
juju ssh nova-cloud-controller/0 "bash keypair.sh"
