#!/bin/bash

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

tmpfile=$(mktemp)

$(scriptPath)/share/novarc > $tmpfile
cat $(scriptPath)/share/common.sh >> $tmpfile
cat $(scriptPath)/share/nova.sh >> $tmpfile

juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL $tmpfile nova-cloud-controller/0:nova.sh
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-cloud-controller/0 "bash nova.sh"
