#!/bin/bash

set -eux

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

mkdir -p $HOME/.kube
mkdir -p $HOME/bin

if [[ $(uname -s) = "Darwin" ]]; then
    KUBE_DEST="/usr/local/bin"
    KUBE_REPO=https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64

    curl -sLO $KUBE_REPO/kubectl
    chmod +x kubectl
    mv kubectl $KUBE_DEST/kubectl
else
    KUBE_DEST="/snap/bin"

    sudo snap install kubectl --classic || true
fi

cp "$(dirname "$0")/kubectl-wrapper" "$HOME/bin/kubectl"
chmod +x "$HOME/bin/kubectl"

setResult "The Kubernetes client utility (kubectl) is now available"
exit 0
