#!/bin/bash

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

tmpfile=$(mktemp)

$(scriptPath)/../novarc > $tmpfile
cat $CONJURE_UP_SPELLSDIR/sdk/common.sh >> $tmpfile
cat $(scriptPath)/neutron.sh >> $tmpfile

juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL $tmpfile nova-cloud-controller/0:neutron.sh
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-cloud-controller/0 "bash neutron.sh"
