#!/bin/bash

set -eu

get_creds() {
    creds_file="$(juju credentials google --format=json | jq -r '.["local-credentials"]["google"]["cloud-credentials"]["'"$JUJU_CREDENTIAL"'"]["details"]["file"]')"
    base64 "$creds_file"
}

enable_cni() {
    if ! juju trust -m "$JUJU_CONTROLLER:$JUJU_MODEL" gcp 2>/dev/null; then
        juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" gcp credentials="$(get_creds)"
    fi
}
