#!/usr/bin/env python3
from conjureup.hooklib.writer import success, fail, error
from conjureup.hooklib import juju


agent_states = juju.agent_states()
agent_states_no_es = []

for row in agent_states:
    if 'elasticsearch' not in row[0]:
        agent_states_no_es.append(row)

error_states = [(unit_name, current_state, workload_message)
                for unit_name, current_state, workload_message in
                agent_states if current_state == 'error']
if len(error_states) > 0:
    error('Deployment error in: {}'.format(error_states))

if all([state == 'active' for _, state, _ in agent_states_no_es]):
    success('Applications are ready')

fail('Applications not ready yet')
