#!/bin/bash
set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

if ! juju wait -wm $JUJU_CONTROLLER:$JUJU_MODEL; then
    exposeResult "Applications did not start successfully" 1 "false"
fi

exposeResult "Applications Ready" 0 "true"
