#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/common.sh

if [ $JUJU_PROVIDERTYPE = "lxd" ] || [ $JUJU_PROVIDERTYPE = "localhost" ]; then
    profilename=$(juju-2.0 switch | cut -d: -f2)
    debug "processing $profilename"
    sed "s/##MODEL##/$profilename/" $SCRIPTPATH/lxd-profile.yaml | lxc profile edit "juju-$profilename"

    RET=$?
    if [ $RET -ne 0 ]; then
        exposeResult "Failed to update lxd profile $profilename" $RET "false"
    else
        exposeResult "Complete" 0 "true"
    fi

fi

exposeResult "Finished pre deploy tasks..." 0 "true"
