#!/bin/bash

set -eu

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

kubeconfig=$(redis-cli get "conjure-up.$CONJURE_UP_SPELL.latest_config_filename")

INFO="$(kubectl --kubeconfig="$kubeconfig" cluster-info | perl -p -e 's/\n/\\n/'| perl -pe 's/\x1b\[[0-9;]*m//g')"

setResult "$INFO"
exit 0
