#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/common.sh

kubectl_cmd=~/kubectl
if [ -f ~/.kube/config.conjure-up ]; then
    kubectl_cmd="$kubectl_cmd --kubeconfig=~/.kube/config.conjure-up"
fi

NODES="$($kubectl_cmd get nodes | perl -p -e 's/\n/\\n/')"
PODS="$($kubectl_cmd get pods | perl -p -e 's/\n/\\n/')"
SERVICES="$($kubectl_cmd get services | perl -p -e 's/\n/\\n/')"
KIBANA_ADDR=$(unitAddress kibana 0)
result="Nodes:\n$NODES\nPods:\n$PODS\nServices:\n$SERVICES\n\nView Kibana at http://$KIBANA_ADDR/"

exposeResult "$result" 0 "true"
