#!/bin/bash

set -eux

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

mkdir -p $HOME/.kube
mkdir -p $HOME/bin

kubeconfig_path=$(autoincrFile "$HOME/.kube/config")
juju scp -m "$JUJU_CONTROLLER:$JUJU_MODEL" kubernetes-master/0:config "$kubeconfig_path"

# Create a unique context for this config
hash=$(genHash)
sed -i "s/juju-context/juju-context-$hash/g" "$kubeconfig_path"

if [[ $(uname -s) = "Darwin" ]]; then
    repo=https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/darwin/amd64/
    curl -sLO $repo/kubectl
    chmod +x kubectl
    mv kubectl /usr/local/bin/kubectl
    curl -sLO $repo/kubefed
    chmod +x kubefed
    mv kubefed /usr/local/bin/kubefed
else
    sudo snap install kubectl --classic || true
    sudo snap install kubefed --classic || true
fi

latest_config_filename="${kubeconfig_path##*/}"
setResult "The Kubernetes client utility is now available, run with \`kubectl --kubeconfig=\$HOME/.kube/$latest_config_filename\`"
exit 0
