#!/bin/bash

# Path to executing script
SCRIPT=$(realpath $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $SCRIPTPATH/common.sh

KUBECTL_PATH=$HOME/conjure-up/kubernetes
mkdir -p $KUBECTL_PATH || true
mkdir -p $HOME/.kube

leaderUnit=$(getLeader kubernetes-master)
debug "Found leader: $leaderUnit"
juju-2.0 scp $leaderUnit:config $HOME/.kube/config
juju-2.0 scp $leaderUnit:kubectl $KUBECTL_PATH/

exposeResult "The Kubernetes client utility is now available at '$KUBECTL_PATH/kubectl'" 0 "true"
