#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

if [[ "$LOGGINGPLUGIN" != "rsyslog" ]]; then
    setStepKey "bundle-remove" "rsyslog.yaml"
    setStepKey "bundle-add" "elg.yaml"
fi

exit 0
