#!/usr/bin/env python3
from conjureup.hooklib.writer import success, fail
from conjureup.hooklib import juju

status = juju.status()
applications = status['applications']['spark']
zeppelin_ip = applications['units']['spark/0']['public-address']

if zeppelin_ip:
    success("Zeppelin UI is now configured "
            "and can be viewed at http://{}:9090".format(zeppelin_ip))
fail("Unable to determine Zeppelin UI URL")
