#!/bin/bash

set -eu

get_creds() {
    endpoint="$(juju clouds --format=json | jq -r '.["'"$JUJU_CLOUD"'"].endpoint')"
    region="$(juju clouds --format=json | jq -r '.["'"$JUJU_CLOUD"'"].regions | keys[0]')"
    juju credentials "$JUJU_CLOUD" --show-secrets --format=json | \
      jq 'if .["local-credentials"] then .["local-credentials"] else .["credentials"] end | .["'"$JUJU_CLOUD"'"]["cloud-credentials"]["'"$JUJU_CREDENTIAL"'"]["details"] | {"auth-url": "'"$endpoint"'", "region": "'"$region"'", "username", "password", "project-name": .["tenant-name"], "user-domain-name", "project-domain-name"}' | base64
}

enable_cni() {
    if ! juju trust -m "$JUJU_CONTROLLER:$JUJU_MODEL" openstack-integrator; then
        >&2 echo "juju-trust not available; falling back to passing credentials via charm config."
        >&2 echo "Note: Charm config can be read by anyone with read access to the model."
        juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" openstack-integrator credentials="$(get_creds)"
    fi
}
