#!/usr/bin/env python3
from conjureup.hooklib import juju
from conjureup.hooklib.writer import success, fail, error
from conjureup.utils import run
from subprocess import CalledProcessError


status = juju.status()
applications = status['applications']['ganglia']
ganglia_ip = applications['units']['ganglia/0']['public-address']

try:
    run('juju expose ganglia', shell=True, check=True)
except CalledProcessError as e:
    log.error(e)
    error("Unable to expose Ganglia: ".format(e))

if ganglia_ip:
    success("Ganglia UI Monitoring is now configured "
            "and can be viewed at http://{}/ganglia".format(ganglia_ip))
fail("Unable to determine Ganglia UI URL")
