#!/usr/bin/env python3
from conjureup.hooklib.writer import success, fail, error
from conjureup.utils import run
from subprocess import CalledProcessError
import logging
import os

JUJU_CONTROLLER = os.environ['JUJU_CONTROLLER']
JUJU_MODEL = os.environ['JUJU_MODEL']
JUJU_CM_STR = "{}:{}".format(JUJU_CONTROLLER, JUJU_MODEL)

log = logging.getLogger('conjureup')
BLOGURL = os.environ.get('BLOGURL', None)

if BLOGURL is not None:
    try:
        run('juju config -m {} ghost url={}'.format(
            JUJU_CM_STR, BLOGURL),
            shell=True, check=True)
        success("Visit your Ghost application at {}".format(BLOGURL))
    except CalledProcessError as e:
        log.error(e)
        error("Unable to set URL for ghost: ".format(e))
else:
    fail("Could not determine a BLOGURL to set")
