#!/bin/bash

set -eu

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

juju config -m $JUJU_CONTROLLER:$JUJU_MODEL ghost url="$BLOGURL"

exposeResult "Visit your Ghost application at $BLOGURL" 0 "true"
