#!/usr/bin/env python3
from conjureup.hooklib.writer import success, fail, error
from conjureup.utils import run
from subprocess import CalledProcessError
import logging
import os

log = logging.getLogger('conjureup')
BLOGURL = os.environ.get('BLOGURL', None)

if BLOGURL is not None:
    try:
        run('juju-2.0 config ghost url={}'.format(BLOGURL),
            shell=True, check=True)
        success("Visit your Ghost application at {}".format(BLOGURL))
    except CalledProcessError as e:
        log.error(e)
        error("Unable to set URL for ghost: ".format(e))
else:
    fail("Could not determine a BLOGURL to set")
