#!/bin/bash

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

tmpfile=$(mktemp)

$SCRIPTPATH/share/novarc > $tmpfile
cat $SCRIPTPATH/share/common.sh >> $tmpfile
cat $SCRIPTPATH/share/glance.sh >> $tmpfile

juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL $tmpfile nova-cloud-controller/0:glance.sh
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL nova-cloud-controller/0 "bash glance.sh"
