#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

if [[ "$JUJU_PROVIDERTYPE" == "localhost" ]]; then
    debug "Running pre-deploy for $CONJURE_UP_SPELL"
    lxc_aa_profile="lxc.aa_profile"
    version=$(lxc --version)
    version_arr=(${version//./ })
    if [[ "${version_arr[0]}" -gt "2" ]]; then
        lxc_aa_profile="lxc.apparmor.profile"
    fi
    cat "$(scriptPath)/lxd-profile.yaml" | sed -e "s/##MODEL##/$JUJU_MODEL/" -e "s/##AA_PROFILE##/$lxc_aa_profile/" | lxc profile edit "juju-$JUJU_MODEL"
fi

setResult "Successful pre-deploy."
exit 0
