#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

if [[ "$MONITORPLUGIN" == "Ganglia" ]]; then
    ip=$(unitAddress ganglia)
    setResult "The Ganglia UI is available at: http://$ip/ganglia."
else
    # gather vars (stripping quotes) for later config and result message
    grafana_url=$(unitAddress grafana)
    grafana_port=$(juju config grafana port | sed -e 's/"//')
    prom_url=$(unitAddress prometheus)
    prom_port=$(juju config prometheus prometheus_registration_port | sed -e 's/"//')
    prom_token=$(juju config prometheus prometheus_registration_authtoken | sed -e 's/"//')

    juju config telegraf promreg_authtoken="$prom_token" \
                         promreg_url="http://$prom_url:$prom_port"
    juju run-action --wait grafana/0 import-dashboard \
      dashboard="$(base64 $(scriptPath)/grafana-telegraf.json)"

    setResult "The Grafana UI is available at: http://$grafana_url:$grafana_port. \
Retrieve the admin password with 'juju run-action --wait grafana/0 get-admin-password'."
fi

exit 0
