#!/bin/bash

set -eu

get_creds() {
    endpoint="$(juju clouds --format=json | jq -r '.["'"$JUJU_CLOUD"'"].endpoint')"
    juju credentials "$JUJU_CLOUD" --show-secrets --format=json | \
      jq 'if .["local-credentials"] then .["local-credentials"] else .["credentials"] end | .["'"$JUJU_CLOUD"'"]["cloud-credentials"]["'"$JUJU_CREDENTIAL"'"]["details"] | {"vsphere_ip": "'"$endpoint"'", "user", "password", "datacenter": "'"$JUJU_REGION"'"}' | base64
}

enable_cni() {
    if ! juju trust -m "$JUJU_CONTROLLER:$JUJU_MODEL" vsphere-integrator; then
        >&2 echo "juju-trust not available; falling back to passing credentials via charm config."
        >&2 echo "Note: Charm config can be read by anyone with read access to the model."
        juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" vsphere-integrator credentials="$(get_creds)"
    fi
}
