#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

if [[ "$NETWORKPLUGIN" == "calico" ]]; then
    setStepKey "bundle-add" "calico.yaml"
    setStepKey "bundle-remove" "flannel.yaml"
fi

exit 0
