#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

export KUBECONFIG=$HOME/.kube/config.$JUJU_MODEL

kubectl apply -f "$(scriptPath)/cdk-rancher-nodeport.yaml"
applicationUnits kubernetes-worker | while read unit; do
    juju run -m "$JUJU_CONTROLLER:$JUJU_MODEL" --unit "$unit" "open-port 30443"
done

worker_0_public_ip=$(unitAddress kubernetes-worker)
setResult "Rancher is now installed and accessible from any worker node at port \
30443 such as https://$worker_0_public_ip:30443. The default username/password is\
admin/admin."

exit 0
