#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

debug "Running pre-deploy for $CONJURE_UP_SPELL to place workers on GPU hardware"
setStepKey "bundle-add" "$(scriptPath)/aws-gpu-workers.yaml"

setResult "Successfully added GPU worker constraints"
exit 0
