#!/bin/bash

set -eu

get_creds() {
    juju credentials aws --show-secrets --format=json | jq -r 'if .["local-credentials"] then .["local-credentials"] else .["credentials"] end | .["aws"]["cloud-credentials"]["'"$JUJU_CREDENTIAL"'"]["details"] | "aws_access_key_id = \(.["access-key"])\naws_secret_access_key = \(.["secret-key"])"' | base64
}

enable_cni() {
    if ! juju trust -m "$JUJU_CONTROLLER:$JUJU_MODEL" aws 2>/dev/null; then
        juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" aws credentials="$(get_creds)"
    fi
}
