#!/bin/bash

set -eu

get_creds() {
    juju credentials aws --show-secrets --format=json | jq -r '.["local-credentials"]["aws"]["cloud-credentials"]["'"$JUJU_CREDENTIAL"'"]["details"] | "aws_access_key_id = \(.["access-key"])\naws_secret_access_key = \(.["secret-key"])"' | base64
}

enable_cni() {
    if ! juju trust aws; then
        juju config aws credentials="$(get_creds)"
    fi
}
