#!/bin/bash

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

tmpfile=$(mktemp)
$(scriptPath)/vars > $tmpfile
cat $(scriptPath)/setup-landscape.sh >> $tmpfile

juju scp -m $JUJU_CONTROLLER:$JUJU_MODEL $tmpfile landscape-server/0:setup-landscape.sh
juju ssh -m $JUJU_CONTROLLER:$JUJU_MODEL landscape-server/0 "bash setup-landscape.sh"
RET=$?

if [ $RET -gt 0 ]; then
    setResult "Unable to register against Landscape server, please check your deployment."
    exit 1
fi

result_message="Landscape is now available, to access visit: https://`juju run --unit haproxy/0 \"unit-get private-address\"`/account/standalone/openstack \n\nlogin: $LDS_EMAIL \npassword: $LDS_PASSWORD"

setResult "$result_message"
exit 0
