#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

export KUBECONFIG=$HOME/.kube/config.$JUJU_MODEL

WORK_DIR=`mktemp -d`

cleanup() {
    rm -rf "$WORK_DIR"
}

echo "Installing Helm CLI"
curl -fsSL -o $WORK_DIR/helm-stable.tar.gz https://storage.googleapis.com/kubernetes-helm/helm-"$HELM_VERSION"-linux-amd64.tar.gz
tar -C $WORK_DIR -zxvf $WORK_DIR/helm-stable.tar.gz
mv $WORK_DIR/linux-amd64/helm $HOME/bin/.helm
echo "KUBECONFIG=$HOME/.kube/config.$JUJU_MODEL $HOME/bin/.helm \$@" > $HOME/bin/helm
chmod +x $HOME/bin/helm


init_count=0
while ! helm init --upgrade; do
    if [[ "$init_count" -gt 5 ]]; then
        break
    fi
    ((init_count=init_count+1))
    sleep 5
done

setResult "Helm installed and ready for use! Be sure to checkout https://helm.sh"

cleanup
exit 0
