#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

if [[ "$MONITORPLUGIN" == "Telegraf/Prometheus/Grafana" ]]; then
    setStepKey "bundle-remove" "ganglia.yaml"
    setStepKey "bundle-add" "tpg.yaml"
fi

exit 0
