#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

if [[ "$JUJU_PROVIDERTYPE" == "localhost" ]]; then
    tmpfile=$(mktemp)

    debug "Running pre-deploy for $CONJURE_UP_SPELL"
    NETWORK=$(getKey "lxd-network-name")
    if [[ "$NETWORK" = "None" ]]; then
        NETWORK="lxdbr0"
    fi
    STORAGE_POOL=$(getKey "lxd-storage-pool")
    if [[ "$STORAGE_POOL" = "None" ]]; then
        STORAGE_POOL="default"
    fi
    lxc network create conjureup0 \
        ipv6.address=none \
        ipv6.nat=false \
        ipv4.address=10.101.0.1/24 \
        ipv4.nat=true || printf "conjureup0 network already exists" && true

    cat <<EOF> "$tmpfile"
name: juju-${JUJU_MODEL}
config:
  boot.autostart: "true"
  security.nesting: "true"
  security.privileged: "true"
  linux.kernel_modules: openvswitch,nbd,ip_tables,ip6_tables,netlink_diag
  raw.lxc: |
    lxc.aa_profile=unconfined
    lxc.mount.auto=sys:rw
devices:
  eth0:
    nictype: bridged
    parent: ${NETWORK}
    type: nic
  eth1:
    nictype: bridged
    parent: conjureup0
    type: nic
  root:
    path: /
    pool: ${STORAGE_POOL}
    type: disk
EOF
    cat "$tmpfile" | lxc profile edit "juju-${JUJU_MODEL}"
fi

setResult "Successful pre-deploy."
exit 0
