services:
  grafana:
    charm: cs:xenial/grafana-11
    constraints: mem=3G
    num_units: 1
    expose: true
  prometheus:
    charm: cs:xenial/prometheus-6
    constraints: mem=3G root-disk=16G
    num_units: 1
  telegraf:
    charm: cs:xenial/telegraf-13
relations:
  - ["prometheus:grafana-source", "grafana:grafana-source"]
  - ["telegraf:prometheus-client", "prometheus:target"]
  - ["kubernetes-master:juju-info", "telegraf:juju-info"]
  - ["kubernetes-worker:juju-info", "telegraf:juju-info"]
