#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

# gather vars (stripping quotes) for later config and result message
proxy_public_ip=$(unitAddress apache2)
es_cluster=$(juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" elasticsearch cluster-name | sed -e 's/"//g')

# Graylog needs a rev proxy vhost and ES cluster name.
juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" apache2 \
  vhost_http_template="$(base64 $(scriptPath)/graylog-vhost.tmpl)"
juju config -m "$JUJU_CONTROLLER:$JUJU_MODEL" graylog \
  elasticsearch_cluster_name="$es_cluster"

setResult "The Graylog UI is accessible at: http://$proxy_public_ip/. \
Retrieve the admin password with 'juju run-action --wait graylog/0 show-admin-password'. \
NOTE: Graylog configuration may still be in progress. It may take up to 5 minutes for \
the web interface to become ready."

exit 0
