#!/bin/bash
set -eux

# Path to executing script
SCRIPT=$(readlink -e $0)

# Directory housing script
SCRIPTPATH=$(dirname $SCRIPT)

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

testLog "Checking for ~/bin/kubectl"
test -f $HOME/bin/kubectl

testLog "Checking for ~/bin/kubectl.$JUJU_MODEL"
test -f $HOME/bin/kubectl.$JUJU_MODEL

testLog "Verifying that the correct kubectl config is used"
egrep -q "config\.$JUJU_MODEL" $HOME/bin/kubectl.$JUJU_MODEL

testLog "Verifying kubenetes master is listening"
master_ip=$(unitAddress "kubernetes-master")
nc -z $master_ip 6443

testLog "Cleaning up configs and binaries"
rm -rf ~/.kube* || true
rm -rf ~/bin/kubectl* || true
