#!/bin/bash
set -eu

. $CONJURE_UP_SPELLSDIR/sdk/common.sh

testLog "Checking for ~/bin/kubectl.$JUJU_MODEL"
test -f $HOME/bin/kubectl.$JUJU_MODEL

master_ip=$(unitAddress "kubernetes-master")
testLog "Verifying kubernetes master ($master_ip) is listening"
nc -z $master_ip 6443

testLog "Cleaning up configs and binaries"
rm -rf ~/.kube* || true
rm -rf ~/bin/kubectl* || true
