#!/usr/bin/env python3

from conjureup.sdk import ua, sh, spec, fail
from conjureup.api import models

test_spec = spec.load()

# sh simple cli runner
for substrate in test_spec['substrates']:
    if substrate in test_spec['credentials']:
        sh("conjure-up ghost {}".format(substrate))

status = models.model_status()

# ua is user agent
ret = ua.get(
    status['applications']['ghost']['units']['ghost/0']['public-address'])

if "Welcome to Ghost" not in ret.text:
    fail("Unable to determine if Ghost is running.")

sh("juju config ghost port=8888", wait=True)

# ua is user agent
ret = ua.get(
    status['applications']['ghost']['units']['ghost/0']['public-address'])

if "Welcome to Ghost" not in ret.text:
    fail("Unable to determine if Ghost is running.")
