#!/usr/bin/env python3
from conjureup.hooklib import juju
from conjureup.hooklib.writer import success, fail, error  # noqa


status = juju.status()
applications = status['applications']['kibana']
ip = applications['units']['kibana/0']['public-address']
if ip:
    success("Kibana is now configured "
            "and can be viewed at http://{}".format(ip))
fail("Unable to determine Kibana URL")
