#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

lb_public_ip=$(unitAddress kubernetes-worker)
kubectl="$(getKey kubectl.dest)"
sed -e s/##PUBLIC_IP##/$lb_public_ip/g $(scriptPath)/cdk-rancher-ingress.yaml | "$kubectl" apply -f -

setResult "Rancher is now installed and accessible from https://rancher.$lb_public_ip.xip.io \
The default username/password is admin/admin."

exit 0
