#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

PATH="$PATH:$HOME/bin"

if [[ $(uname -s) = "Darwin" ]]; then
    platform="darwin"
else
    platform="linux"
fi

ksonnet_repo="https://github.com/ksonnet/ksonnet/releases/download/v$KS_VERSION"
ksonnet_file="ks_${KS_VERSION}_${platform}_amd64.tar.gz"

work_dir="$(mktemp -d)"
curl -fsSL -o "$work_dir/$ksonnet_file" "$ksonnet_repo/$ksonnet_file"
tar -C "$work_dir" -zxvf "$work_dir/$ksonnet_file" 1>&2
mv "$work_dir/ks_${KS_VERSION}_${platform}_amd64/ks" "$HOME/bin/ks"

rm -rf "$work_dir"

setResult "Ksonnet installed and ready for use!"

exit 0
