#!/bin/bash

set -eux

. "$CONJURE_UP_SPELLSDIR/sdk/common.sh"

deis_implementation="$(dirname "$0")/$JUJU_PROVIDERTYPE/install-deis-workflow"
if [[ -f "$deis_implementation" ]]; then
    . "$deis_implementation"
    enable_deis
    setResult "Deis is installed"
else
    setResult "Deis is not available for this provider."
    exit 1
fi
exit 0
