#!/usr/bin/env python3
from conjureup.hooklib import juju
from conjureup.hooklib.writer import success, fail


status = juju.status()
applications = status['applications']['ganglia']
ganglia_ip = applications['units']['ganglia/0']['public-address']

if ganglia_ip:
    success("Ganglia UI Monitoring is now configured "
            "and can be viewed at http://{}/ganglia".format(ganglia_ip))
fail("Unable to determine Ganglia UI URL")
